#!/bin/bash
if [ $# -eq 0 ]; then
  echo "no summoner name supplied"
  exit 1
fi
curl https://na1.api.riotgames.com/lol/summoner/v3/summoners/by-name/`echo "$@" | sed -e 's/ /%20/'`?api_key=RGAPI-0e7f4fc7-2ecc-460f-9e1e-9cf75f8e175f
